### ISSUE TITLE
relay_vlans cannot be set with a vlan object or int id 

### ISSUE THREAD

**Issue by envasquez** [maas/python-libmaas#180]
While trying to wrap setting a vlan's relay_vlan attribute I was not able to accomplish this with the latest python-libmaas code.

If I use an in (vid or vlan.id): I get this error:

```
2018-05-23-17:28:17 DEBUG Setting vlan:  - relay_vlan to 2733
value type: <class 'int'>
value = 2733
Traceback (most recent call last):
  File "foundation/bin/maas-config-networks", line 333, in <module>
    sys.exit(main())
  File "foundation/bin/maas-config-networks", line 324, in main
    fabric_vlans=fabric_vlans)
  File "foundation/bin/maas-config-networks", line 242, in apply_vlans_to_fabric
    set_vlan_attr(vlan, attr.lower(), value)
  File "foundation/bin/maas-config-networks", line 222, in set_vlan_attr
    setattr(vlan, attr, value)
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/viscera/__init__.py", line 363, in __setattr__
    ret = super(Object, self).__setattr__(name, value)
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/viscera/__init__.py", line 759, in __set__
    datum = self.value_to_datum(instance, value)
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/viscera/__init__.py", line 888, in value_to_datum
    "must be %s, not %s" % (self.cls, type(value).__name__))
TypeError: must be Vlan, not int
Makefile:106: recipe for target 'networkconfig' failed
make: *** [networkconfig] Error 1
```

When I try to set the relay_vlan to a vlan object, I get this error:

```
2018-05-23-17:23:30 DEBUG Setting vlan:  - relay_vlan to Vlan
value type: <class 'origin.Vlan'>
value = Vlan
Traceback (most recent call last):
  File "foundation/bin/maas-config-networks", line 333, in <module>
    sys.exit(main())
  File "foundation/bin/maas-config-networks", line 324, in main
    fabric_vlans=fabric_vlans)
  File "foundation/bin/maas-config-networks", line 242, in apply_vlans_to_fabric
    set_vlan_attr(vlan, attr.lower(), value)
  File "foundation/bin/maas-config-networks", line 223, in set_vlan_attr
    vlan.save()
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/utils/async.py", line 49, in wrapper
    result = eventloop.run_until_complete(result)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/viscera/vlans.py", line 108, in save
    self._data = await self._handler.update(**update_data)
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/bones/__init__.py", line 302, in __call__
    response = await self.bind(**params).call(**data)
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/bones/__init__.py", line 390, in call
    uri, body, headers = self.prepare(data)
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/bones/__init__.py", line 420, in prepare
    self.action.op, self.action.method, self.uri, data)
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/utils/__init__.py", line 111, in prepare_payload
    message = build_multipart_message(data)
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/utils/multipart.py", line 124, in build_multipart_message
    for payload in make_payloads(name, content):
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/utils/multipart.py", line 114, in make_payloads
    for payload in make_payloads(name, part):
  File "/home/ubuntu/cpe-deployments/libmaas-venv/lib/python3.5/site-packages/maas/client/utils/multipart.py", line 118, in make_payloads
    "%r is unrecognised: %r" % (name, content))
AssertionError: 'relay_vlan' is unrecognised: <Fabric id=3 (unloaded)>
Makefile:106: recipe for target 'networkconfig' failed
```

**Comment by jhobbs** [comment]
16:54 < blake_r> jhobbs: needs to be fixed
16:54 < blake_r> jhobbs: not much to comment
16:54 < blake_r> jhobbs: just need to fix it

**Comment by mpontillo** [comment]
I reproduced the first portion of this in a unit test as follows:

```diff
diff --git a/maas/client/viscera/tests/test_vlans.py b/maas/client/viscera/tests/test_vlans.py
index a1301fd..09688de 100644
--- a/maas/client/viscera/tests/test_vlans.py
+++ b/maas/client/viscera/tests/test_vlans.py
@@ -191,3 +191,30 @@ class TestVlan(TestCase):
         Vlan._handler.update.assert_called_once_with(
             fabric_id=fabric_id, vid=vid, _vid=new_vid)
         self.assertThat(new_vid, Equals(new_vid))
+
+    def test__vlan_update_relay_vlan(self):
+        origin = make_origin()
+        Fabric, Vlan = origin.Fabric, origin.Vlan
+        Vlan._handler.params = ['fabric_id', 'vid']
+        fabric_id = random.randint(1, 100)
+        vlan_id = random.randint(5001, 6000)
+        vid = random.randint(100, 200)
+        vlan = Vlan({
+            "id": vlan_id,
+            "fabric_id": fabric_id,
+            "vid": vid,
+        })
+        relay_vlan = Vlan({
+            "id": vlan_id + 1,
+            "fabric_id": fabric_id,
+            "vid": vid + 10,
+        })
+        vlan.relay_vlan = vlan_id + 1
+        Vlan._handler.update.return_value = {
+            "id": vlan_id,
+            "vid": vid,
+        }
+        vlan.save()
+        Vlan._handler.update.assert_called_once_with(
+            fabric_id=fabric_id, vid=vid, _vid=vid, relay_vlan=relay_vlan.id)
+        self.assertThat(vlan.relay_vlan.id, Equals(relay_vlan.id))
```

The fix, however, is not so obvious; it feels to me like a design change that will have to be more carefully considered.

We have to consider the history here: URL pattern that MAAS historically used for VLANs was in the form:

    .../fabrics/<fabric-id>/vlans/<vid>

That is, a VID can be identified uniquely only within a particular fabric. As a secondary URL for VIDs, MAAS also supports URLs of the form:

    .../vlans/<vlan-id>

Currently, the `python-libmaas` code is not aware of the second method of referring to the VLAN ID. I tried using the `alt_pk` mechanism to specify the `id` field as an alternate primary key, but I don't think that's a complete test. (It still fails.) So more will have to change in the `python-libmaas` for this to work.

That being the case, I'm going to focus only on the second part of this issue. As for the first issue, I agree that it would be nice to set this field to an integer ID and have it "just work", but I'm not sure if that should be tracked in a separate issue and/or an out-of-band discussion.

For the record: for VLANs, we can assume that an integer under 5000 will need to be qualified with a fabric ID in order to be a primary key, while IDs over >= 5000 can be assumed to uniquely identify the VLAN.
