### ISSUE TITLE
Machine status_ attributes throw AttributeError: sub<attribute_name>

### ISSUE THREAD

**Issue by brendan-donegan** [maas/python-libmaas#24]
After getting Machines from the origin, if I try to access the status_ attributes, I get an exception like:

> > > machines[0].status_name
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/brendand/src/alburnum-maas-client/alburnum/maas/viscera/**init**.py", line 378, in **get**
> > >     raise AttributeError(self.name)
> > > AttributeError: substatus_name

Accessing machines[0].status returns fine, as does any other attribute (even when it includes an underscore)

**Comment by brendan-donegan** [comment]
This was fixed
