### ISSUE TITLE
Imcompatible with python 3.10

### ISSUE THREAD

**Issue by alptbz** [maas/python-libmaas#263]
`
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from maas.client import login
  File "venv\lib\site-packages\maas\client\__init__.py", line 5, in <module>
    from .utils.maas_async import asynchronous
  File "venv\lib\site-packages\maas\client\utils\__init__.py", line 29, in <module>
    from collections import Iterable, namedtuple
ImportError: cannot import name 'Iterable' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)
`
As of python 3.10 a few things have been moved:
https://docs.python.org/3.9/library/collections.html

**Comment by albertodonato** [comment]
Fixed in #271
