### ISSUE TITLE
Unable to connect to MAAS behind HA Proxy without port 5240 open

### ISSUE THREAD

**Issue by samschmitt22** [maas/python-libmaas#286]
We are running MaaS behind HAProxy as described in the HA docs for MaaS. However there seems to be some sort of implicit redirect back to port 5240 for the API, and this port is not open between the client and our MaaS servers. 

Example: 
```python 
 client = maas.client.connect("http://example.com/MAAS/", apikey="<apikey>")
myself = client.users.whoami()
```

This will hang and eventually fail with:
```
Traceback (most recent call last):
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 60] Connect call failed ('<IP>', 5240)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/maas/client/utils/maas_async.py", line 43, in wrapper
    result = eventloop.run_until_complete(result)
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/maas/client/viscera/users.py", line 13, in whoami
    data = await cls._handler.whoami()
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/maas/client/bones/__init__.py", line 309, in __call__
    response = await self.bind(**params).call(**data)
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/maas/client/bones/__init__.py", line 461, in dispatch
    response = await session.request(
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/sschmitt/.virtualenvs/openstack_venv/lib/python3.9/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host example.com:5240 ssl:default [Connect call failed ('<IP>', 5240)]
```

**Comment by cjohnston1158** [comment]
Similar to [LP#2009186](https://bugs.launchpad.net/maas/+bug/2009186)

**Comment by troyanov** [comment]
Please try out this temporary fix https://github.com/maas/python-libmaas/pull/287

The correct way would be to [fix](https://code.launchpad.net/~troyanov/maas/+git/maas/+merge/438884) it on MAAS side.

**Comment by cjohnston1158** [comment]
The fix in MAAS has resolved this issue for me without #287

**Comment by troyanov** [comment]
@samschmitt22 can you please try `3.2/edge` or `3.3.1` and tell us if that resolves the issue for you?

**Comment by samschmitt22** [comment]
I'm hitting the same error after upgrading to 3.3.1

**Comment by samschmitt22** [comment]
The changes in #287 did fix it for me however.

**Comment by r00ta** [comment]
https://github.com/maas/python-libmaas/pull/287 has been merged
