### ISSUE TITLE
Please support creating openvswitch bridges

### ISSUE THREAD

**Issue by greenmoss** [maas/python-libmaas#295]
From the MaaS UI, we can create openvswitch bridges. However, we can not from python-libmaas.

I am using python-libmaas from  master of this git repo, dated 2023-10-23, commit `fec3b5023f9d618ba61e9d9108a345300216d8c3`.

Example:

```
>>> machine.interfaces.create(maas.client.enum.InterfaceType.BRIDGE, name='br0', parent=interface, bridge_type='ovs')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nu/venvs/maas-api/lib/python3.11/site-packages/maas/client/utils/maas_async.py", line 43, in wrapper
    result = eventloop.run_until_complete(result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/nu/venvs/maas-api/lib/python3.11/site-packages/maas/client/viscera/__init__.py", line 498, in _create
    new_obj = await super_cls.create(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nu/venvs/maas-api/lib/python3.11/site-packages/maas/client/utils/maas_async.py", line 40, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: InterfacesType.create() got an unexpected keyword argument 'bridge_type'
```

**Comment by alanbach** [comment]
I think this would be a good addition. I also always use OpenVSwitch bridges.
