### ISSUE TITLE
TypeError: Unions cannot be used with issubclass()

### ISSUE THREAD

**Issue by fabianbaier** [maas/python-libmaas#58]
Following the documentation I ran into this error: `TypeError: Unions cannot be used with issubclass().`

I created the environment on my Mac with conda: `conda create --name galaxy python=3.5`
Switched into the env and installed via: `pip install git+https://github.com/maas/python-libmaas.git`
Until here everything was successful. When I tried to start `maas --help` I get:

```(galaxy) Fabians-MacBook-Pro-3:galaxy fabianbaier$ maas --help
Traceback (most recent call last):
  File "/Users/fabianbaier/anaconda/envs/galaxy/bin/maas", line 11, in <module>
    load_entry_point('python-libmaas==0.3.1', 'console_scripts', 'maas')()
  File "/Users/fabianbaier/anaconda/envs/galaxy/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/Users/fabianbaier/anaconda/envs/galaxy/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/Users/fabianbaier/anaconda/envs/galaxy/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2258, in load
  File "/Users/fabianbaier/anaconda/envs/galaxy/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/Users/fabianbaier/anaconda/envs/galaxy/lib/python3.5/site-packages/maas/client/flesh/__init__.py", line 31, in <module>
    from .. import (
  File "/Users/fabianbaier/anaconda/envs/galaxy/lib/python3.5/site-packages/maas/client/bones/__init__.py", line 22, in <module>
    from . import helpers
  File "/Users/fabianbaier/anaconda/envs/galaxy/lib/python3.5/site-packages/maas/client/bones/helpers.py", line 28, in <module>
    from ..utils.profiles import Profile
  File "/Users/fabianbaier/anaconda/envs/galaxy/lib/python3.5/site-packages/maas/client/utils/profiles.py", line 24, in <module>
    from .types import JSONObject
  File "/Users/fabianbaier/anaconda/envs/galaxy/lib/python3.5/site-packages/maas/client/utils/types.py", line 30, in <module>
    assert issubclass(str, JSONValue)
  File "/Users/fabianbaier/anaconda/envs/galaxy/lib/python3.5/typing.py", line 770, in __subclasscheck__
    raise TypeError("Unions cannot be used with issubclass().")
TypeError: Unions cannot be used with issubclass().```

**Comment by fabianbaier** [comment]
Issue still persist with python 3.5.3 after #60. However I got it working by downgrading to python 3.5.2.

**Comment by allenap** [comment]
Fabian, sorry. I didn't put enough effort into reproducing the issue before and I assumed that my fix would work, and I have been caught out. I think PR #64 will fix this issue properly.
