### ISSUE TITLE
client.login only works with when endpoint is a hostname and not an IP address

### ISSUE THREAD

**Issue by roaksoax** [maas/python-libmaas#80]
Log-in doesn't work with IP addresses, it only works with hostnames.

>>> client = login("http://10.10.10.10:5240/MAAS/", username="user", password="user")
Traceback (most recent call last):
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/bones/helpers.py", line 249, in _obtain_token
    cookie for cookie in session.cookie_jar
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/utils/async.py", line 49, in wrapper
    result = eventloop.run_until_complete(result)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/__init__.py", line 43, in login
    url, username=username, password=password, insecure=insecure)
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/viscera/__init__.py", line 603, in login
    url=url, username=username, password=password, insecure=insecure)
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/bones/__init__.py", line 76, in login
    url=url, username=username, password=password, insecure=insecure)
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/bones/helpers.py", line 187, in login
    url.geturl(), username, password, insecure=insecure)
RuntimeError: coroutine raised StopIteration
>>> client = login("http://192.168.10.27:5240/MAAS/", username="admin", password="admin")
Traceback (most recent call last):
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/bones/helpers.py", line 249, in _obtain_token
    cookie for cookie in session.cookie_jar
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/utils/async.py", line 49, in wrapper
    result = eventloop.run_until_complete(result)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/__init__.py", line 43, in login
    url, username=username, password=password, insecure=insecure)
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/viscera/__init__.py", line 603, in login
    url=url, username=username, password=password, insecure=insecure)
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/bones/__init__.py", line 76, in login
    url=url, username=username, password=password, insecure=insecure)
  File "/home/ubuntu/amc/lib/python3.5/site-packages/maas/client/bones/helpers.py", line 187, in login
    url.geturl(), username, password, insecure=insecure)
RuntimeError: coroutine raised StopIteration

**Comment by blakerouse** [comment]
This was resolved when the login was improved to use the API instead of the frontend.
